services:
  frontend:
    build: ./frontend
    container_name: dicom-frontend
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://backend:3001/graphql
      - PORT=5173
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    command: ["npm", "run", "dev"]

  backend:
    build: ./backend
    container_name: dicom-backend
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - DB_HOST=dicom-db
      - DB_USER=dicomuser
      - DB_PASSWORD=dicompassword
      - DB_NAME=dicomdb
      - DB_PORT=3306 
      - PORT=3001
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      db:
        condition: service_healthy
    command: ["node", "server.js"]

  db:
    image: mysql:8
    container_name: dicom-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: dicomdb
      MYSQL_USER: dicomuser
      MYSQL_PASSWORD: dicompassword
    ports:
      - "3310:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
      start_period: 20s

volumes:
  db_data:
